spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;MODE=MySQL;DATABASE_TO_UPPER=FALSE
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
